<?php
 // created: 2018-01-26 17:10:12
$dictionary['dsm_dnc_historic']['fields']['contact_name']['required']=false;
$dictionary['dsm_dnc_historic']['fields']['contact_name']['source']='non-db';
$dictionary['dsm_dnc_historic']['fields']['contact_name']['name']='contact_name';
$dictionary['dsm_dnc_historic']['fields']['contact_name']['vname']='LBL_CONTACT_NAME';
$dictionary['dsm_dnc_historic']['fields']['contact_name']['type']='relate';
$dictionary['dsm_dnc_historic']['fields']['contact_name']['rname']='name';
$dictionary['dsm_dnc_historic']['fields']['contact_name']['id_name']='contact_id';
$dictionary['dsm_dnc_historic']['fields']['contact_name']['join_name']='contacts';
$dictionary['dsm_dnc_historic']['fields']['contact_name']['link']='contacts';
$dictionary['dsm_dnc_historic']['fields']['contact_name']['table']='contacts';
$dictionary['dsm_dnc_historic']['fields']['contact_name']['isnull']='true';
$dictionary['dsm_dnc_historic']['fields']['contact_name']['module']='Contacts';
$dictionary['dsm_dnc_historic']['fields']['contact_name']['audited']=false;
$dictionary['dsm_dnc_historic']['fields']['contact_name']['massupdate']=false;
$dictionary['dsm_dnc_historic']['fields']['contact_name']['duplicate_merge']='enabled';
$dictionary['dsm_dnc_historic']['fields']['contact_name']['duplicate_merge_dom_value']='1';
$dictionary['dsm_dnc_historic']['fields']['contact_name']['merge_filter']='disabled';
$dictionary['dsm_dnc_historic']['fields']['contact_name']['unified_search']=false;
$dictionary['dsm_dnc_historic']['fields']['contact_name']['calculated']=false;
