USE [SugarCRMBridge]
GO
/****** Object:  Table [dbo].[pushToVoxco]    Script Date: 03/12/2018 10:03:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[pushToVoxco](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SugarCRMID] [varchar](100) NOT NULL,
	[dbName] [varchar](25) NOT NULL,
	[ResLang] [int] NOT NULL,
	[ResBlocked] [bit] NOT NULL,
	[ResWaveImportNo] [int] NOT NULL,
	[ResActive] [bit] NOT NULL,
	[RpsRegionI] [varchar](50) NOT NULL,
	[RpsPhoneI] [varchar](20) NOT NULL,
	[action] [varchar](20) NULL,
	[modified] [datetime] NULL,
 CONSTRAINT [PK_pushToVoxco] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
SET IDENTITY_INSERT [dbo].[pushToVoxco] ON
INSERT [dbo].[pushToVoxco] ([ID], [SugarCRMID], [dbName], [ResLang], [ResBlocked], [ResWaveImportNo], [ResActive], [RpsRegionI], [RpsPhoneI], [action], [modified]) VALUES (1, N'12345-67890-12345-67890', N'voxco_project_11366', 1, 0, 1, 1, N'117', N'5146188359', N'add', CAST(0x0000A89300F117C6 AS DateTime))
SET IDENTITY_INSERT [dbo].[pushToVoxco] OFF
/****** Object:  Table [dbo].[pushToSugarCRM]    Script Date: 03/12/2018 10:03:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[pushToSugarCRM](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[HisRespondent] [varchar](10) NOT NULL,
	[HisCallNumber] [int] NOT NULL,
	[HisResult] [varchar](2) NOT NULL,
	[HisCallDate] [datetime] NOT NULL,
	[HisCallDuration] [int] NOT NULL,
	[HisPhone] [varchar](20) NOT NULL,
	[HisCaseResult] [varchar](2) NOT NULL,
	[ResLang] [int] NULL,
	[ResBlocked] [bit] NULL,
	[ResWaveImportNo] [int] NULL,
	[ResProjectID] [int] NULL,
	[ResModifiedBy] [int] NULL,
	[ResModified] [datetime] NULL,
	[ResActive] [bit] NULL,
	[RpsQuestion] [varchar](32) NULL,
	[RpsContent] [varchar](100) NULL,
	[RpsSource] [varchar](max) NULL,
	[RpsCollectMode] [int] NULL,
	[SugarCRMID] [varchar](100) NOT NULL,
	[dbName] [varchar](255) NOT NULL,
 CONSTRAINT [PK_pushToSugarCRM] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
SET IDENTITY_INSERT [dbo].[pushToSugarCRM] ON
INSERT [dbo].[pushToSugarCRM] ([ID], [HisRespondent], [HisCallNumber], [HisResult], [HisCallDate], [HisCallDuration], [HisPhone], [HisCaseResult], [ResLang], [ResBlocked], [ResWaveImportNo], [ResProjectID], [ResModifiedBy], [ResModified], [ResActive], [RpsQuestion], [RpsContent], [RpsSource], [RpsCollectMode], [SugarCRMID], [dbName]) VALUES (5, N'0000000015', 1, N'RS', CAST(0x0000A893013DB7B0 AS DateTime), 0, N'', N'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'', N'Voxco_Project_11366')
INSERT [dbo].[pushToSugarCRM] ([ID], [HisRespondent], [HisCallNumber], [HisResult], [HisCallDate], [HisCallDuration], [HisPhone], [HisCaseResult], [ResLang], [ResBlocked], [ResWaveImportNo], [ResProjectID], [ResModifiedBy], [ResModified], [ResActive], [RpsQuestion], [RpsContent], [RpsSource], [RpsCollectMode], [SugarCRMID], [dbName]) VALUES (6, N'0000000016', 1, N'', CAST(0x0000A89301409394 AS DateTime), 4, N'514-704-0297', N'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'', N'Voxco_Project_11366')
INSERT [dbo].[pushToSugarCRM] ([ID], [HisRespondent], [HisCallNumber], [HisResult], [HisCallDate], [HisCallDuration], [HisPhone], [HisCaseResult], [ResLang], [ResBlocked], [ResWaveImportNo], [ResProjectID], [ResModifiedBy], [ResModified], [ResActive], [RpsQuestion], [RpsContent], [RpsSource], [RpsCollectMode], [SugarCRMID], [dbName]) VALUES (7, N'0000000016', 2, N'', CAST(0x0000A89400D90314 AS DateTime), 10, N'514-704-0297', N'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'', N'Voxco_Project_11366')
INSERT [dbo].[pushToSugarCRM] ([ID], [HisRespondent], [HisCallNumber], [HisResult], [HisCallDate], [HisCallDuration], [HisPhone], [HisCaseResult], [ResLang], [ResBlocked], [ResWaveImportNo], [ResProjectID], [ResModifiedBy], [ResModified], [ResActive], [RpsQuestion], [RpsContent], [RpsSource], [RpsCollectMode], [SugarCRMID], [dbName]) VALUES (8, N'0000000016', 3, N'', CAST(0x0000A89400D98B04 AS DateTime), 14, N'514-704-0297', N'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'', N'Voxco_Project_11366')
INSERT [dbo].[pushToSugarCRM] ([ID], [HisRespondent], [HisCallNumber], [HisResult], [HisCallDate], [HisCallDuration], [HisPhone], [HisCaseResult], [ResLang], [ResBlocked], [ResWaveImportNo], [ResProjectID], [ResModifiedBy], [ResModified], [ResActive], [RpsQuestion], [RpsContent], [RpsSource], [RpsCollectMode], [SugarCRMID], [dbName]) VALUES (9, N'0000000016', 4, N'', CAST(0x0000A89400D9B084 AS DateTime), 3, N'514-704-0297', N'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'', N'Voxco_Project_11366')
INSERT [dbo].[pushToSugarCRM] ([ID], [HisRespondent], [HisCallNumber], [HisResult], [HisCallDate], [HisCallDuration], [HisPhone], [HisCaseResult], [ResLang], [ResBlocked], [ResWaveImportNo], [ResProjectID], [ResModifiedBy], [ResModified], [ResActive], [RpsQuestion], [RpsContent], [RpsSource], [RpsCollectMode], [SugarCRMID], [dbName]) VALUES (10, N'0000000016', 5, N'', CAST(0x0000A89400D9CA4C AS DateTime), 8, N'514-704-0297', N'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'', N'Voxco_Project_11366')
INSERT [dbo].[pushToSugarCRM] ([ID], [HisRespondent], [HisCallNumber], [HisResult], [HisCallDate], [HisCallDuration], [HisPhone], [HisCaseResult], [ResLang], [ResBlocked], [ResWaveImportNo], [ResProjectID], [ResModifiedBy], [ResModified], [ResActive], [RpsQuestion], [RpsContent], [RpsSource], [RpsCollectMode], [SugarCRMID], [dbName]) VALUES (11, N'0000000016', 6, N'', CAST(0x0000A89400DB1AA0 AS DateTime), 2, N'514-704-0297', N'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'', N'Voxco_Project_11366')
INSERT [dbo].[pushToSugarCRM] ([ID], [HisRespondent], [HisCallNumber], [HisResult], [HisCallDate], [HisCallDuration], [HisPhone], [HisCaseResult], [ResLang], [ResBlocked], [ResWaveImportNo], [ResProjectID], [ResModifiedBy], [ResModified], [ResActive], [RpsQuestion], [RpsContent], [RpsSource], [RpsCollectMode], [SugarCRMID], [dbName]) VALUES (12, N'0000000016', 7, N'', CAST(0x0000A89400DC54B0 AS DateTime), 2, N'514-704-0297', N'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'', N'Voxco_Project_11366')
INSERT [dbo].[pushToSugarCRM] ([ID], [HisRespondent], [HisCallNumber], [HisResult], [HisCallDate], [HisCallDuration], [HisPhone], [HisCaseResult], [ResLang], [ResBlocked], [ResWaveImportNo], [ResProjectID], [ResModifiedBy], [ResModified], [ResActive], [RpsQuestion], [RpsContent], [RpsSource], [RpsCollectMode], [SugarCRMID], [dbName]) VALUES (13, N'0000000016', 8, N'RF', CAST(0x0000A89400DCC65C AS DateTime), 6, N'5147040297', N'RF', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'', N'Voxco_Project_11366')
INSERT [dbo].[pushToSugarCRM] ([ID], [HisRespondent], [HisCallNumber], [HisResult], [HisCallDate], [HisCallDuration], [HisPhone], [HisCaseResult], [ResLang], [ResBlocked], [ResWaveImportNo], [ResProjectID], [ResModifiedBy], [ResModified], [ResActive], [RpsQuestion], [RpsContent], [RpsSource], [RpsCollectMode], [SugarCRMID], [dbName]) VALUES (14, N'0000000016', 9, N'RF', CAST(0x0000A89400DE2394 AS DateTime), 6, N'5147040297', N'RF', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'', N'Voxco_Project_11366')
INSERT [dbo].[pushToSugarCRM] ([ID], [HisRespondent], [HisCallNumber], [HisResult], [HisCallDate], [HisCallDuration], [HisPhone], [HisCaseResult], [ResLang], [ResBlocked], [ResWaveImportNo], [ResProjectID], [ResModifiedBy], [ResModified], [ResActive], [RpsQuestion], [RpsContent], [RpsSource], [RpsCollectMode], [SugarCRMID], [dbName]) VALUES (15, N'0000000016', 10, N'W2', CAST(0x0000A89400DF6A88 AS DateTime), 150, N'5147040297', N'W2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'', N'Voxco_Project_11366')
INSERT [dbo].[pushToSugarCRM] ([ID], [HisRespondent], [HisCallNumber], [HisResult], [HisCallDate], [HisCallDuration], [HisPhone], [HisCaseResult], [ResLang], [ResBlocked], [ResWaveImportNo], [ResProjectID], [ResModifiedBy], [ResModified], [ResActive], [RpsQuestion], [RpsContent], [RpsSource], [RpsCollectMode], [SugarCRMID], [dbName]) VALUES (16, N'0000000016', 11, N'W2', CAST(0x0000A89400E0298C AS DateTime), 4, N'514-704-0297', N'W2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'', N'Voxco_Project_11366')
INSERT [dbo].[pushToSugarCRM] ([ID], [HisRespondent], [HisCallNumber], [HisResult], [HisCallDate], [HisCallDuration], [HisPhone], [HisCaseResult], [ResLang], [ResBlocked], [ResWaveImportNo], [ResProjectID], [ResModifiedBy], [ResModified], [ResActive], [RpsQuestion], [RpsContent], [RpsSource], [RpsCollectMode], [SugarCRMID], [dbName]) VALUES (17, N'0000000016', 12, N'W2', CAST(0x0000A89400E04930 AS DateTime), 3, N'514-704-0297', N'W2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'', N'Voxco_Project_11366')
INSERT [dbo].[pushToSugarCRM] ([ID], [HisRespondent], [HisCallNumber], [HisResult], [HisCallDate], [HisCallDuration], [HisPhone], [HisCaseResult], [ResLang], [ResBlocked], [ResWaveImportNo], [ResProjectID], [ResModifiedBy], [ResModified], [ResActive], [RpsQuestion], [RpsContent], [RpsSource], [RpsCollectMode], [SugarCRMID], [dbName]) VALUES (18, N'0000000016', 13, N'W2', CAST(0x0000A89400E091D8 AS DateTime), 6, N'514-704-0297', N'W2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'', N'Voxco_Project_11366')
INSERT [dbo].[pushToSugarCRM] ([ID], [HisRespondent], [HisCallNumber], [HisResult], [HisCallDate], [HisCallDuration], [HisPhone], [HisCaseResult], [ResLang], [ResBlocked], [ResWaveImportNo], [ResProjectID], [ResModifiedBy], [ResModified], [ResActive], [RpsQuestion], [RpsContent], [RpsSource], [RpsCollectMode], [SugarCRMID], [dbName]) VALUES (19, N'0000000016', 14, N'W2', CAST(0x0000A89400E0B62C AS DateTime), 4, N'514-704-0297', N'W2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'', N'Voxco_Project_11366')
INSERT [dbo].[pushToSugarCRM] ([ID], [HisRespondent], [HisCallNumber], [HisResult], [HisCallDate], [HisCallDuration], [HisPhone], [HisCaseResult], [ResLang], [ResBlocked], [ResWaveImportNo], [ResProjectID], [ResModifiedBy], [ResModified], [ResActive], [RpsQuestion], [RpsContent], [RpsSource], [RpsCollectMode], [SugarCRMID], [dbName]) VALUES (20, N'0000000016', 15, N'W2', CAST(0x0000A89400E13390 AS DateTime), 17, N'514-704-0297', N'W2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'', N'Voxco_Project_11366')
INSERT [dbo].[pushToSugarCRM] ([ID], [HisRespondent], [HisCallNumber], [HisResult], [HisCallDate], [HisCallDuration], [HisPhone], [HisCaseResult], [ResLang], [ResBlocked], [ResWaveImportNo], [ResProjectID], [ResModifiedBy], [ResModified], [ResActive], [RpsQuestion], [RpsContent], [RpsSource], [RpsCollectMode], [SugarCRMID], [dbName]) VALUES (21, N'0000000016', 16, N'RF', CAST(0x0000A89400E1DB24 AS DateTime), 4, N'5147040297', N'RF', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'', N'Voxco_Project_11366')
INSERT [dbo].[pushToSugarCRM] ([ID], [HisRespondent], [HisCallNumber], [HisResult], [HisCallDate], [HisCallDuration], [HisPhone], [HisCaseResult], [ResLang], [ResBlocked], [ResWaveImportNo], [ResProjectID], [ResModifiedBy], [ResModified], [ResActive], [RpsQuestion], [RpsContent], [RpsSource], [RpsCollectMode], [SugarCRMID], [dbName]) VALUES (22, N'0000000016', 17, N'W2', CAST(0x0000A89400E1E22C AS DateTime), 45, N'5147040297', N'W2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'', N'Voxco_Project_11366')
INSERT [dbo].[pushToSugarCRM] ([ID], [HisRespondent], [HisCallNumber], [HisResult], [HisCallDate], [HisCallDuration], [HisPhone], [HisCaseResult], [ResLang], [ResBlocked], [ResWaveImportNo], [ResProjectID], [ResModifiedBy], [ResModified], [ResActive], [RpsQuestion], [RpsContent], [RpsSource], [RpsCollectMode], [SugarCRMID], [dbName]) VALUES (23, N'0000000016', 18, N'W2', CAST(0x0000A89400E224F8 AS DateTime), 11, N'514-704-0297', N'W2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'', N'Voxco_Project_11366')
INSERT [dbo].[pushToSugarCRM] ([ID], [HisRespondent], [HisCallNumber], [HisResult], [HisCallDate], [HisCallDuration], [HisPhone], [HisCaseResult], [ResLang], [ResBlocked], [ResWaveImportNo], [ResProjectID], [ResModifiedBy], [ResModified], [ResActive], [RpsQuestion], [RpsContent], [RpsSource], [RpsCollectMode], [SugarCRMID], [dbName]) VALUES (24, N'0000000016', 19, N'RF', CAST(0x0000A89400E23A10 AS DateTime), 2, N'5147040297', N'RF', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'', N'Voxco_Project_11366')
INSERT [dbo].[pushToSugarCRM] ([ID], [HisRespondent], [HisCallNumber], [HisResult], [HisCallDate], [HisCallDuration], [HisPhone], [HisCaseResult], [ResLang], [ResBlocked], [ResWaveImportNo], [ResProjectID], [ResModifiedBy], [ResModified], [ResActive], [RpsQuestion], [RpsContent], [RpsSource], [RpsCollectMode], [SugarCRMID], [dbName]) VALUES (25, N'0000000016', 20, N'RF', CAST(0x0000A89400E23EC0 AS DateTime), 3, N'5147040297', N'RF', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'', N'Voxco_Project_11366')
INSERT [dbo].[pushToSugarCRM] ([ID], [HisRespondent], [HisCallNumber], [HisResult], [HisCallDate], [HisCallDuration], [HisPhone], [HisCaseResult], [ResLang], [ResBlocked], [ResWaveImportNo], [ResProjectID], [ResModifiedBy], [ResModified], [ResActive], [RpsQuestion], [RpsContent], [RpsSource], [RpsCollectMode], [SugarCRMID], [dbName]) VALUES (26, N'0000000016', 21, N'RF', CAST(0x0000A89400E297D0 AS DateTime), 4, N'5147040297', N'RF', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'', N'Voxco_Project_11366')
INSERT [dbo].[pushToSugarCRM] ([ID], [HisRespondent], [HisCallNumber], [HisResult], [HisCallDate], [HisCallDuration], [HisPhone], [HisCaseResult], [ResLang], [ResBlocked], [ResWaveImportNo], [ResProjectID], [ResModifiedBy], [ResModified], [ResActive], [RpsQuestion], [RpsContent], [RpsSource], [RpsCollectMode], [SugarCRMID], [dbName]) VALUES (27, N'0000000016', 22, N'RF', CAST(0x0000A89400E2B06C AS DateTime), 11, N'514-704-0297', N'RF', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'', N'Voxco_Project_11366')
INSERT [dbo].[pushToSugarCRM] ([ID], [HisRespondent], [HisCallNumber], [HisResult], [HisCallDate], [HisCallDuration], [HisPhone], [HisCaseResult], [ResLang], [ResBlocked], [ResWaveImportNo], [ResProjectID], [ResModifiedBy], [ResModified], [ResActive], [RpsQuestion], [RpsContent], [RpsSource], [RpsCollectMode], [SugarCRMID], [dbName]) VALUES (28, N'0000000016', 23, N'RF', CAST(0x0000A89400E2F6BC AS DateTime), 3, N'5147040297', N'RF', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'', N'Voxco_Project_11366')
INSERT [dbo].[pushToSugarCRM] ([ID], [HisRespondent], [HisCallNumber], [HisResult], [HisCallDate], [HisCallDuration], [HisPhone], [HisCaseResult], [ResLang], [ResBlocked], [ResWaveImportNo], [ResProjectID], [ResModifiedBy], [ResModified], [ResActive], [RpsQuestion], [RpsContent], [RpsSource], [RpsCollectMode], [SugarCRMID], [dbName]) VALUES (29, N'0000000016', 24, N'RF', CAST(0x0000A89400E2FDC4 AS DateTime), 3, N'5147040297', N'RF', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'', N'Voxco_Project_11366')
INSERT [dbo].[pushToSugarCRM] ([ID], [HisRespondent], [HisCallNumber], [HisResult], [HisCallDate], [HisCallDuration], [HisPhone], [HisCaseResult], [ResLang], [ResBlocked], [ResWaveImportNo], [ResProjectID], [ResModifiedBy], [ResModified], [ResActive], [RpsQuestion], [RpsContent], [RpsSource], [RpsCollectMode], [SugarCRMID], [dbName]) VALUES (30, N'0000000016', 25, N'RF', CAST(0x0000A89400E30BD4 AS DateTime), 2, N'5147040297', N'RF', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'', N'Voxco_Project_11366')
INSERT [dbo].[pushToSugarCRM] ([ID], [HisRespondent], [HisCallNumber], [HisResult], [HisCallDate], [HisCallDuration], [HisPhone], [HisCaseResult], [ResLang], [ResBlocked], [ResWaveImportNo], [ResProjectID], [ResModifiedBy], [ResModified], [ResActive], [RpsQuestion], [RpsContent], [RpsSource], [RpsCollectMode], [SugarCRMID], [dbName]) VALUES (31, N'0000000016', 26, N'RF', CAST(0x0000A89400E3BDF4 AS DateTime), 2, N'5147040297', N'RF', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'', N'Voxco_Project_11366')
INSERT [dbo].[pushToSugarCRM] ([ID], [HisRespondent], [HisCallNumber], [HisResult], [HisCallDate], [HisCallDuration], [HisPhone], [HisCaseResult], [ResLang], [ResBlocked], [ResWaveImportNo], [ResProjectID], [ResModifiedBy], [ResModified], [ResActive], [RpsQuestion], [RpsContent], [RpsSource], [RpsCollectMode], [SugarCRMID], [dbName]) VALUES (32, N'0000000016', 27, N'P1', CAST(0x0000A89400E44CEC AS DateTime), 0, N'5147040297', N'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'', N'Voxco_Project_11366')
INSERT [dbo].[pushToSugarCRM] ([ID], [HisRespondent], [HisCallNumber], [HisResult], [HisCallDate], [HisCallDuration], [HisPhone], [HisCaseResult], [ResLang], [ResBlocked], [ResWaveImportNo], [ResProjectID], [ResModifiedBy], [ResModified], [ResActive], [RpsQuestion], [RpsContent], [RpsSource], [RpsCollectMode], [SugarCRMID], [dbName]) VALUES (33, N'0000000016', 28, N'P1', CAST(0x0000A89400E4D3B0 AS DateTime), 0, N'5147040297', N'', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'', N'Voxco_Project_11366')
INSERT [dbo].[pushToSugarCRM] ([ID], [HisRespondent], [HisCallNumber], [HisResult], [HisCallDate], [HisCallDuration], [HisPhone], [HisCaseResult], [ResLang], [ResBlocked], [ResWaveImportNo], [ResProjectID], [ResModifiedBy], [ResModified], [ResActive], [RpsQuestion], [RpsContent], [RpsSource], [RpsCollectMode], [SugarCRMID], [dbName]) VALUES (34, N'0000000016', 29, N'RF', CAST(0x0000A89400E53170 AS DateTime), 5, N'5147040297', N'RF', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'', N'Voxco_Project_11366')
INSERT [dbo].[pushToSugarCRM] ([ID], [HisRespondent], [HisCallNumber], [HisResult], [HisCallDate], [HisCallDuration], [HisPhone], [HisCaseResult], [ResLang], [ResBlocked], [ResWaveImportNo], [ResProjectID], [ResModifiedBy], [ResModified], [ResActive], [RpsQuestion], [RpsContent], [RpsSource], [RpsCollectMode], [SugarCRMID], [dbName]) VALUES (35, N'0000000016', 30, N'W2', CAST(0x0000A89400E571E4 AS DateTime), 6, N'5147040297', N'W2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'', N'Voxco_Project_11366')
INSERT [dbo].[pushToSugarCRM] ([ID], [HisRespondent], [HisCallNumber], [HisResult], [HisCallDate], [HisCallDuration], [HisPhone], [HisCaseResult], [ResLang], [ResBlocked], [ResWaveImportNo], [ResProjectID], [ResModifiedBy], [ResModified], [ResActive], [RpsQuestion], [RpsContent], [RpsSource], [RpsCollectMode], [SugarCRMID], [dbName]) VALUES (36, N'0000000016', 31, N'RF', CAST(0x0000A89400E58954 AS DateTime), 2, N'5147040297', N'RF', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'', N'Voxco_Project_11366')
INSERT [dbo].[pushToSugarCRM] ([ID], [HisRespondent], [HisCallNumber], [HisResult], [HisCallDate], [HisCallDuration], [HisPhone], [HisCaseResult], [ResLang], [ResBlocked], [ResWaveImportNo], [ResProjectID], [ResModifiedBy], [ResModified], [ResActive], [RpsQuestion], [RpsContent], [RpsSource], [RpsCollectMode], [SugarCRMID], [dbName]) VALUES (37, N'0000000016', 32, N'01', CAST(0x0000A89400E81994 AS DateTime), 16, N'5147040297', N'01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'', N'Voxco_Project_11366')
INSERT [dbo].[pushToSugarCRM] ([ID], [HisRespondent], [HisCallNumber], [HisResult], [HisCallDate], [HisCallDuration], [HisPhone], [HisCaseResult], [ResLang], [ResBlocked], [ResWaveImportNo], [ResProjectID], [ResModifiedBy], [ResModified], [ResActive], [RpsQuestion], [RpsContent], [RpsSource], [RpsCollectMode], [SugarCRMID], [dbName]) VALUES (38, N'0000000016', 33, N'RF', CAST(0x0000A89400E9D360 AS DateTime), 14, N'5147040297', N'RF', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'', N'Voxco_Project_11366')
INSERT [dbo].[pushToSugarCRM] ([ID], [HisRespondent], [HisCallNumber], [HisResult], [HisCallDate], [HisCallDuration], [HisPhone], [HisCaseResult], [ResLang], [ResBlocked], [ResWaveImportNo], [ResProjectID], [ResModifiedBy], [ResModified], [ResActive], [RpsQuestion], [RpsContent], [RpsSource], [RpsCollectMode], [SugarCRMID], [dbName]) VALUES (39, N'0000000016', 34, N'NP', CAST(0x0000A89400EA34A4 AS DateTime), 7, N'5147040297', N'NP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'', N'Voxco_Project_11366')
INSERT [dbo].[pushToSugarCRM] ([ID], [HisRespondent], [HisCallNumber], [HisResult], [HisCallDate], [HisCallDuration], [HisPhone], [HisCaseResult], [ResLang], [ResBlocked], [ResWaveImportNo], [ResProjectID], [ResModifiedBy], [ResModified], [ResActive], [RpsQuestion], [RpsContent], [RpsSource], [RpsCollectMode], [SugarCRMID], [dbName]) VALUES (41, N'0000000016', 35, N'A3', CAST(0x0000A89501677324 AS DateTime), 4, N'5147040297', N'A3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'', N'Voxco_Project_11366')
INSERT [dbo].[pushToSugarCRM] ([ID], [HisRespondent], [HisCallNumber], [HisResult], [HisCallDate], [HisCallDuration], [HisPhone], [HisCaseResult], [ResLang], [ResBlocked], [ResWaveImportNo], [ResProjectID], [ResModifiedBy], [ResModified], [ResActive], [RpsQuestion], [RpsContent], [RpsSource], [RpsCollectMode], [SugarCRMID], [dbName]) VALUES (43, N'0000000016', 36, N'A3', CAST(0x0000A89501677324 AS DateTime), 5, N'5147040297', N'A3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'', N'Voxco_Project_11366')
INSERT [dbo].[pushToSugarCRM] ([ID], [HisRespondent], [HisCallNumber], [HisResult], [HisCallDate], [HisCallDuration], [HisPhone], [HisCaseResult], [ResLang], [ResBlocked], [ResWaveImportNo], [ResProjectID], [ResModifiedBy], [ResModified], [ResActive], [RpsQuestion], [RpsContent], [RpsSource], [RpsCollectMode], [SugarCRMID], [dbName]) VALUES (51, N'0000000016', 41, N'A4', CAST(0x0000A89501677324 AS DateTime), 5, N'5147040297', N'A3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'qwerty_123_4456', N'Voxco_Project_11366')
SET IDENTITY_INSERT [dbo].[pushToSugarCRM] OFF
