<?php
 // created: 2018-01-26 17:10:12
$dictionary['Contact']['fields']['dsm_dnc_name']['required']=false;
$dictionary['Contact']['fields']['dsm_dnc_name']['source']='non-db';
$dictionary['Contact']['fields']['dsm_dnc_name']['name']='dsm_dnc_name';
$dictionary['Contact']['fields']['dsm_dnc_name']['vname']='LBL_DSM_DNC_NAME';
$dictionary['Contact']['fields']['dsm_dnc_name']['type']='relate';
$dictionary['Contact']['fields']['dsm_dnc_name']['rname']='name';
$dictionary['Contact']['fields']['dsm_dnc_name']['id_name']='dsm_dnc_id';
$dictionary['Contact']['fields']['dsm_dnc_name']['table']='dsm_dnc';
$dictionary['Contact']['fields']['dsm_dnc_name']['isnull']='true';
$dictionary['Contact']['fields']['dsm_dnc_name']['module']='dsm_dnc';
$dictionary['Contact']['fields']['dsm_dnc_name']['audited']=false;
$dictionary['Contact']['fields']['dsm_dnc_name']['massupdate']=false;
$dictionary['Contact']['fields']['dsm_dnc_name']['duplicate_merge']='enabled';
$dictionary['Contact']['fields']['dsm_dnc_name']['duplicate_merge_dom_value']='1';
$dictionary['Contact']['fields']['dsm_dnc_name']['merge_filter']='disabled';
$dictionary['Contact']['fields']['dsm_dnc_name']['unified_search']=false;
$dictionary['Contact']['fields']['dsm_dnc_name']['calculated']=false;
$dictionary['Contact']['fields']['dsm_dnc_name']['studio']='visible';
