<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  'built_in_version' => '7.10.2.0',
  'acceptable_sugar_versions' => 
  array (
    0 => '',
  ),
  'acceptable_sugar_flavors' => 
  array (
    0 => 'ENT',
    1 => 'ULT',
  ),
  'readme' => '',
  'key' => 'dsm',
  'author' => '',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'DNC_Suivi_Modules',
  'published_date' => '2018-01-31 08:00:47',
  'type' => 'module',
  'version' => 1517385647,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'DNC_Suivi_Modules',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'dsm_dnc',
      'class' => 'dsm_dnc',
      'path' => 'modules/dsm_dnc/dsm_dnc.php',
      'tab' => true,
    ),
    1 => 
    array (
      'module' => 'dsm_dnc_historic',
      'class' => 'dsm_dnc_historic',
      'path' => 'modules/dsm_dnc_historic/dsm_dnc_historic.php',
      'tab' => true,
    ),
    2 => 
    array (
      'module' => 'dsm_suivi_de_vente',
      'class' => 'dsm_suivi_de_vente',
      'path' => 'modules/dsm_suivi_de_vente/dsm_suivi_de_vente.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
  ),
  'relationships' => 
  array (
  ),
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/dsm_dnc',
      'to' => 'modules/dsm_dnc',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/dsm_dnc_historic',
      'to' => 'modules/dsm_dnc_historic',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/dsm_suivi_de_vente',
      'to' => 'modules/dsm_suivi_de_vente',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
  ),
  'image_dir' => '<basepath>/icons',
);