<?php
 // created: 2018-01-24 19:48:06
$dictionary['dsm_dnc_historic']['fields']['source_details']['required']=false;
$dictionary['dsm_dnc_historic']['fields']['source_details']['source']='non-db';
$dictionary['dsm_dnc_historic']['fields']['source_details']['name']='source_details';
$dictionary['dsm_dnc_historic']['fields']['source_details']['vname']='LBL_SOURCE_DETAILS';
$dictionary['dsm_dnc_historic']['fields']['source_details']['type']='relate';
$dictionary['dsm_dnc_historic']['fields']['source_details']['massupdate']=false;
$dictionary['dsm_dnc_historic']['fields']['source_details']['default']=NULL;
$dictionary['dsm_dnc_historic']['fields']['source_details']['no_default']=false;
$dictionary['dsm_dnc_historic']['fields']['source_details']['comments']='';
$dictionary['dsm_dnc_historic']['fields']['source_details']['help']='';
$dictionary['dsm_dnc_historic']['fields']['source_details']['importable']='true';
$dictionary['dsm_dnc_historic']['fields']['source_details']['duplicate_merge']='enabled';
$dictionary['dsm_dnc_historic']['fields']['source_details']['duplicate_merge_dom_value']='1';
$dictionary['dsm_dnc_historic']['fields']['source_details']['audited']=true;
$dictionary['dsm_dnc_historic']['fields']['source_details']['reportable']=true;
$dictionary['dsm_dnc_historic']['fields']['source_details']['unified_search']=false;
$dictionary['dsm_dnc_historic']['fields']['source_details']['merge_filter']='disabled';
$dictionary['dsm_dnc_historic']['fields']['source_details']['calculated']=false;
$dictionary['dsm_dnc_historic']['fields']['source_details']['len']='255';
$dictionary['dsm_dnc_historic']['fields']['source_details']['size']='20';
$dictionary['dsm_dnc_historic']['fields']['source_details']['id_name']='user_id';
$dictionary['dsm_dnc_historic']['fields']['source_details']['ext2']='Users';
$dictionary['dsm_dnc_historic']['fields']['source_details']['module']='Users';
$dictionary['dsm_dnc_historic']['fields']['source_details']['rname']='name';
$dictionary['dsm_dnc_historic']['fields']['source_details']['quicksearch']='enabled';
$dictionary['dsm_dnc_historic']['fields']['source_details']['studio']='visible';
$dictionary['dsm_dnc_historic']['fields']['source_details']['id']='dsm_dnc_historicsource_details';

 ?>