<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  'built_in_version' => '8.*',
  'acceptable_sugar_versions' => 
  array (
    0 => '8.*',
  ),
  'acceptable_sugar_flavors' => 
  array (
    0 => 'ENT',
    1 => 'ULT',
  ),
  'readme' => '',
  'key' => 'rt',
  'author' => 'rolustech',
  'description' => 'DEV-1040 and DEV-1047',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'DEV-1040 and DEV-1047 1.0',
  'published_date' => '2018-08-20 19:31:00',
  'type' => 'module',
  'version' => '1.0.1',
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'DEV-1040_and_Dev-1047_1.0',
  'copy' => 
  array (
    array (
      'from' => '<basepath>/custom/Extension/modules/Schedulers/Ext/ScheduledTasks/meetingAssignationWorkflow.php',
      'to' => 'custom/Extension/modules/Schedulers/Ext/ScheduledTasks/meetingAssignationWorkflow.php',
    ),
    array (
      'from' => '<basepath>/custom/clients/base/api/AppointmentApi.php',
      'to' => 'custom/clients/base/api/AppointmentApi.php',
    ),
    array (
      'from' => '<basepath>/custom/modules/Meetings/clients/base/api/CreateMeetingsApi.php',
      'to' => 'custom/modules/Meetings/clients/base/api/CreateMeetingsApi.php',
    ),
  )
);
