<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  'built_in_version' => '7.10.2.0',
  'acceptable_sugar_versions' => 
  array (
    0 => '',
  ),
  'acceptable_sugar_flavors' => 
  array (
    0 => 'ENT',
    1 => 'ULT',
  ),
  'readme' => '',
  'key' => 'dsm',
  'author' => '',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Customizations',
  'published_date' => '2018-02-15 11:00:00',
  'type' => 'module',
  'version' => 1517385647,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'Customizations',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/custom/Extension/application/Ext/JSGroupings/addFullCalenderPlugin.php',
      'to' => 'custom/Extension/application/Ext/JSGroupings/addFullCalenderPlugin.php',
    ),
    1 => 
    array (
      'from' => '<basepath>/custom/javascript/calendar/fullcalendar.min.js',
      'to' => 'custom/javascript/calendar/fullcalendar.min.js',
    ),
    2 => 
    array (
      'from' => '<basepath>/custom/themes/css/fullcalendar.min.css',
      'to' => 'custom/themes/css/fullcalendar.min.css',
    ),
    3 => 
    array (
      'from' => '<basepath>/custom/themes/css/fullcalendar.print.min.css',
      'to' => 'custom/themes/css/fullcalendar.print.min.css',
    ),
    4 => 
    array (
      'from' => '<basepath>/custom/modules/Meetings/clients/base/api/CreateMeetingsApi.php',
      'to' => 'custom/modules/Meetings/clients/base/api/CreateMeetingsApi.php',
    ),
    5 => 
    array (
      'from' => '<basepath>/custom/modules/Meetings/clients/base/layouts/full-calendar/full-calendar.php',
      'to' => 'custom/modules/Meetings/clients/base/layouts/full-calendar/full-calendar.php',
    ),
    6 => 
    array (
      'from' => '<basepath>/custom/modules/Meetings/clients/base/views/full-calendar/full-calendar.js',
      'to' => 'custom/modules/Meetings/clients/base/views/full-calendar/full-calendar.js',
    ),
    7 => 
    array (
      'from' => '<basepath>/custom/modules/Meetings/clients/base/views/full-calendar/full-calendar.hbs',
      'to' => 'custom/modules/Meetings/clients/base/views/full-calendar/full-calendar.hbs',
    ),
    8 => 
    array (
      'from' => '<basepath>/custom/Extension/modules/Meetings/Ext/clients/base/menus/header/salesRepSchedule.php',
      'to' => 'custom/Extension/modules/Meetings/Ext/clients/base/menus/header/salesRepSchedule.php',
    ),
    9 => 
    array (
      'from' => '<basepath>/custom/Extension/application/Ext/Language/en_us.salesRepSchedule.php',
      'to' => 'custom/Extension/application/Ext/Language/en_us.salesRepSchedule.php',
    ),
    10 => 
    array (
      'from' => '<basepath>/custom/Extension/application/Ext/Language/fr_FR.salesRepSchedule.php',
      'to' => 'custom/Extension/application/Ext/Language/fr_FR.salesRepSchedule.php',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (

    ),
  ),
);