<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  'built_in_version' => '8.*',
  'acceptable_sugar_versions' => 
  array (
    0 => '8.*',
  ),
  'acceptable_sugar_flavors' => 
  array (
    0 => 'ENT',
    1 => 'ULT',
  ),
  'readme' => '',
  'key' => 'rt',
  'author' => 'rolustech',
  'description' => 'Customizations for Solarcan',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Solarcan Customization 1.0.1',
  'published_date' => '2018-08-20 19:31:00',
  'type' => 'module',
  'version' => '1.0.1',
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'solarcan_customization_1.0.1',
    'platforms' => array(
        array(
            'from' => '<basepath>/custom/Extension/application/Ext/Platforms/portal-integration.php',
        )
    ),
  'copy' => 
  array (
    array (
      'from' => '<basepath>/custom/Extension/application/Ext/JSGroupings/addFullCalenderPlugin.php',
      'to' => 'custom/Extension/application/Ext/JSGroupings/addFullCalenderPlugin.php',
    ),
    array (
      'from' => '<basepath>/custom/javascript/calendar/fullcalendar.min.js',
      'to' => 'custom/javascript/calendar/fullcalendar.min.js',
    ),
    array (
      'from' => '<basepath>/custom/themes/css/fullcalendar.min.css',
      'to' => 'custom/themes/css/fullcalendar.min.css',
    ),
    array (
      'from' => '<basepath>/custom/themes/css/fullcalendar.print.min.css',
      'to' => 'custom/themes/css/fullcalendar.print.min.css',
    ),
    array (
      'from' => '<basepath>/custom/modules/Meetings/clients/base/api/CreateMeetingsApi.php',
      'to' => 'custom/modules/Meetings/clients/base/api/CreateMeetingsApi.php',
    ),
    array (
      'from' => '<basepath>/custom/modules/Meetings/clients/base/layouts/full-calendar/full-calendar.php',
      'to' => 'custom/modules/Meetings/clients/base/layouts/full-calendar/full-calendar.php',
    ),
    array (
      'from' => '<basepath>/custom/modules/Meetings/clients/base/views/full-calendar/full-calendar.js',
      'to' => 'custom/modules/Meetings/clients/base/views/full-calendar/full-calendar.js',
    ),
    array (
      'from' => '<basepath>/custom/modules/Meetings/clients/base/views/full-calendar/full-calendar.hbs',
      'to' => 'custom/modules/Meetings/clients/base/views/full-calendar/full-calendar.hbs',
    ),
    array (
      'from' => '<basepath>/custom/Extension/modules/Meetings/Ext/clients/base/menus/header/salesRepSchedule.php',
      'to' => 'custom/Extension/modules/Meetings/Ext/clients/base/menus/header/salesRepSchedule.php',
    ),
    array (
      'from' => '<basepath>/custom/Extension/modules/Meetings/Ext/Language/en_us.telemarketer.php',
      'to' => 'custom/Extension/modules/Meetings/Ext/Language/en_us.telemarketer.php',
    ),
    array (
      'from' => '<basepath>/custom/Extension/modules/Meetings/Ext/Vardefs/tm_telemarketers.php',
      'to' => 'custom/Extension/modules/Meetings/Ext/Vardefs/tm_telemarketers.php',
    ),
    array (
      'from' => '<basepath>/custom/Extension/modules/tm_telemarketers/Ext/clients/base/layouts/subpanels/meetings.php',
      'to' => 'custom/Extension/modules/tm_telemarketers/Ext/clients/base/layouts/subpanels/meetings.php',
    ),
    array (
      'from' => '<basepath>/custom/Extension/modules/tm_telemarketers/Ext/Language/en_us.meetings.php',
      'to' => 'custom/Extension/modules/tm_telemarketers/Ext/Language/en_us.meetings.php',
    ),
    array (
      'from' => '<basepath>/custom/Extension/modules/tm_telemarketers/Ext/Vardefs/meetings.php',
      'to' => 'custom/Extension/modules/tm_telemarketers/Ext/Vardefs/meetings.php',
    ),
    array (
      'from' => '<basepath>/custom/Extension/application/Ext/Language/en_us.salesRepSchedule.php',
      'to' => 'custom/Extension/application/Ext/Language/en_us.salesRepSchedule.php',
    ),
    array (
      'from' => '<basepath>/custom/Extension/application/Ext/Language/fr_FR.salesRepSchedule.php',
      'to' => 'custom/Extension/application/Ext/Language/fr_FR.salesRepSchedule.php',
    ),
    //////////
    array (
      'from' => '<basepath>/custom/Extension/modules/Administration/Ext/Administration/PortalConfig.php',
      'to' => 'custom/Extension/modules/Administration/Ext/Administration/PortalConfig.php',
    ),
    array (
      'from' => '<basepath>/custom/clients/base/api/AppointmentApi.php',
      'to' => 'custom/clients/base/api/AppointmentApi.php',
    ),
    array (
      'from' => '<basepath>/custom/clients/base/views/portal-config/',
      'to' => 'custom/clients/base/views/portal-config/',
    ),
    array (
      'from' => '<basepath>/custom/include/helpers/UtHelper.php',
      'to' => 'custom/include/helpers/UtHelper.php',
    ),
    array (
      'from' => '<basepath>/custom/clients/base/layouts/portal-config/portal-config.php',
      'to' => 'custom/clients/base/layouts/portal-config/portal-config.php',
    ),
    array (
      'from' => '<basepath>/custom/Extension/modules/Schedulers/Ext/ScheduledTasks/ContactsDNCUpdate.php',
      'to' => 'custom/Extension/modules/Schedulers/Ext/ScheduledTasks/ContactsDNCUpdate.php',
    ),
    array (
      'from' => '<basepath>/custom/modules/Import/views/view.last.php',
      'to' => 'custom/modules/Import/views/view.last.php',
    ),
    array (
      'from' => '<basepath>/custom/modules/Import/views/view.step4.php',
      'to' => 'custom/modules/Import/views/view.step4.php',
    ),
    array (
      'from' => '<basepath>/custom/modules/Import/views/view.undo.php',
      'to' => 'custom/modules/Import/views/view.undo.php',
    ),
    array (
      'from' => '<basepath>/custom/Extension/modules/Schedulers/Ext/ScheduledTasks/meetingAssignationWorkflow.php',
      'to' => 'custom/Extension/modules/Schedulers/Ext/ScheduledTasks/meetingAssignationWorkflow.php',
    ),
    array (
      'from' => '<basepath>/custom/Extension/modules/Schedulers/Ext/Language/en_us.meetingAssignationWorkflow.php',
      'to' => 'custom/Extension/modules/Schedulers/Ext/Language/en_us.meetingAssignationWorkflow.php',
    ),
    array (
      'from' => '<basepath>/custom/Extension/modules/Meetings/Ext/LogicHooks/MeetingsHooks.php',
      'to' => 'custom/Extension/modules/Meetings/Ext/LogicHooks/MeetingsHooks.php',
    ),
    array (
      'from' => '<basepath>/custom/modules/Meetings/MeetingsHooksImpl.php',
      'to' => 'custom/modules/Meetings/MeetingsHooksImpl.php',
    ),
    array (
      'from' => '<basepath>/custom/Extension/modules/Opportunities/Ext/LogicHooks/OpportunitiesHooks.php',
      'to' => 'custom/Extension/modules/Opportunities/Ext/LogicHooks/OpportunitiesHooks.php',
    ),
    array (
      'from' => '<basepath>/custom/modules/Opportunities/OpportunitiesHooksImpl.php',
      'to' => 'custom/modules/Opportunities/OpportunitiesHooksImpl.php',
    ),
    array (
      'from' => '<basepath>/custom/Extension/modules/Meetings/Ext/Vardefs/acls.php',
      'to' => 'custom/Extension/modules/Meetings/Ext/Vardefs/acls.php',
    ),
    array (
      'from' => '<basepath>/custom/data/acl/SugarACLFieldOverride.php',
      'to' => 'custom/data/acl/SugarACLFieldOverride.php',
    ),
    ///////////
    array (
      'from' => '<basepath>/custom/Extension/application/Ext/Platforms/voxco-integration.php',
      'to' => 'custom/Extension/application/Ext/Platforms/voxco-integration.php',
    ),
    array (
      'from' => '<basepath>/custom/clients/base/api/BulkImportApi.php',
      'to' => 'custom/clients/base/api/BulkImportApi.php',
    ),
    array (
      'from' => '<basepath>/custom/clients/base/api/CampaignListApi.php',
      'to' => 'custom/clients/base/api/CampaignListApi.php',
    ),
    array (
      'from' => '<basepath>/custom/include/helpers/CampaignListHelper.php',
      'to' => 'custom/include/helpers/CampaignListHelper.php',
    ),
    array (
      'from' => '<basepath>/custom/include/bulkimport/BulkImport.php',
      'to' => 'custom/include/bulkimport/BulkImport.php',
    ),
    array (
      'from' => '<basepath>/custom/modules/Contacts/clients/base/api/ContactsPortalApi.php',
      'to' => 'custom/modules/Contacts/clients/base/api/ContactsPortalApi.php',
    ),
  ),
  'language' => 
  array (
    array(
        'from' => '<basepath>/custom/Extension/application/Ext/Language/en_us.lang.php',
        'to_module' => 'application',
        'language' => 'en_us',
    ),
    array(
        'from' => '<basepath>/custom/Extension/application/Ext/Language/fr_FR.lang.php',
        'to_module' => 'application',
        'language' => 'fr_FR',
    ),
  ),
    'post_install' => array(
        '<basepath>/scripts/post_install.php',
    )
);